//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glazecs.Modules.ASR.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AsrResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AsrResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glazecs.Modules.ASR.Resources.Languages.AsrResources", typeof(AsrResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transcription was cancelled..
        /// </summary>
        public static string ASR_Cancelled {
            get {
                return ResourceManager.GetString("ASR_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на chunks.
        /// </summary>
        public static string ASR_Chunks {
            get {
                return ResourceManager.GetString("ASR_Chunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transcription completed successfully..
        /// </summary>
        public static string ASR_Completed_Success {
            get {
                return ResourceManager.GetString("ASR_Completed_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The specified file could not be found. Check the path..
        /// </summary>
        public static string ASR_Error_File_Not_Found {
            get {
                return ResourceManager.GetString("ASR_Error_File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select a file first..
        /// </summary>
        public static string ASR_Error_No_File {
            get {
                return ResourceManager.GetString("ASR_Error_No_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select a recognition service..
        /// </summary>
        public static string ASR_Error_No_Service {
            get {
                return ResourceManager.GetString("ASR_Error_No_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select an audio file....
        /// </summary>
        public static string ASR_FilePath_Placeholder {
            get {
                return ResourceManager.GetString("ASR_FilePath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initialization was canceled by the user..
        /// </summary>
        public static string ASR_Initialization_Cancelled {
            get {
                return ResourceManager.GetString("ASR_Initialization_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initialization was successful..
        /// </summary>
        public static string ASR_Initialized_Success {
            get {
                return ResourceManager.GetString("ASR_Initialized_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The automatic speech recognition service has started initializing..
        /// </summary>
        public static string ASR_Initializing_Started {
            get {
                return ResourceManager.GetString("ASR_Initializing_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to load the model.
        /// </summary>
        public static string ASR_Model_Download_Failed {
            get {
                return ResourceManager.GetString("ASR_Model_Download_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model downloaded successfully.
        /// </summary>
        public static string ASR_Model_Downloaded_Success {
            get {
                return ResourceManager.GetString("ASR_Model_Downloaded_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No transcription results yet.
        /// </summary>
        public static string ASR_No_Result_Yet {
            get {
                return ResourceManager.GetString("ASR_No_Result_Yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing.
        /// </summary>
        public static string ASR_Processing {
            get {
                return ResourceManager.GetString("ASR_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Recognition Service.
        /// </summary>
        public static string ASR_Service_Label {
            get {
                return ResourceManager.GetString("ASR_Service_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel recognition.
        /// </summary>
        public static string ASR_Tooltip_Cancel {
            get {
                return ResourceManager.GetString("ASR_Tooltip_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initialize the service.
        /// </summary>
        public static string ASR_Tooltip_Initialize {
            get {
                return ResourceManager.GetString("ASR_Tooltip_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can enter the path manually or select an audio file using the button on the right..
        /// </summary>
        public static string ASR_Tooltip_Select_File {
            get {
                return ResourceManager.GetString("ASR_Tooltip_Select_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start recognition.
        /// </summary>
        public static string ASR_Tooltip_Start {
            get {
                return ResourceManager.GetString("ASR_Tooltip_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
    }
}
